const std = @import("std");

pub fn build(b: *std.Build) void {
    _ = b;
}

pub fn stubSharedLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    name: []const u8,
    soversion: u32,
    symbols: []const []const u8,
) *std.Build.Step.Compile {
    var src: std.Io.Writer.Allocating = .init(b.allocator);
    defer src.deinit();
    for (symbols) |sym|
        src.writer.print("export fn {s}() callconv(.c) void {{}}\n", .{sym}) catch @panic("OOM");

    const wf = b.addWriteFiles();
    const src_file = wf.add(b.fmt("stub_{s}.zig", .{name}), src.written());

    return b.addLibrary(.{
        .name = name,
        .linkage = .dynamic,
        .version = .{ .major = soversion, .minor = 0, .patch = 0 },
        .root_module = b.createModule(.{
            .root_source_file = src_file,
            .target = target,
            .optimize = optimize,
        }),
    });
}

pub const freetype_stub_symbols = [_][]const u8{
    "FT_Done_Face",
    "FT_Done_FreeType",
    "FT_Get_Char_Index",
    "FT_Get_Sfnt_Table",
    "FT_Init_FreeType",
    "FT_Load_Char",
    "FT_New_Face",
    "FT_New_Memory_Face",
    "FT_Outline_Get_BBox",
    "FT_Outline_Transform",
    "FT_Render_Glyph",
    "FT_Select_Size",
    "FT_Set_Pixel_Sizes",
};

pub const fontconfig_stub_symbols = [_][]const u8{
    "FcCharSetAddChar",
    "FcCharSetCreate",
    "FcCharSetDestroy",
    "FcCharSetHasChar",
    "FcConfigDestroy",
    "FcConfigSubstitute",
    "FcDefaultSubstitute",
    "FcFontList",
    "FcFontMatch",
    "FcFontSetDestroy",
    "FcFontSort",
    "FcInitLoadConfigAndFonts",
    "FcNameParse",
    "FcObjectSetAdd",
    "FcObjectSetCreate",
    "FcObjectSetDestroy",
    "FcPatternAddBool",
    "FcPatternAddCharSet",
    "FcPatternAddInteger",
    "FcPatternAddString",
    "FcPatternCreate",
    "FcPatternDestroy",
    "FcPatternGetBool",
    "FcPatternGetCharSet",
    "FcPatternGetInteger",
    "FcPatternGetString",
};

// GL functions sokol_gfx links. This is sokol's _SG_GL_FUNCS X-macro list.
// see src/sokol/c/sokol_gfx.h
pub const gl_stub_symbols = [_][]const u8{
    "glActiveTexture",
    "glAttachShader",
    "glBindBuffer",
    "glBindBufferBase",
    "glBindBufferRange",
    "glBindFramebuffer",
    "glBindImageTexture",
    "glBindRenderbuffer",
    "glBindSampler",
    "glBindTexture",
    "glBindVertexArray",
    "glBlendColor",
    "glBlendEquationSeparate",
    "glBlendFunc",
    "glBlendFuncSeparate",
    "glBlitFramebuffer",
    "glBufferData",
    "glBufferSubData",
    "glCheckFramebufferStatus",
    "glClearBufferfi",
    "glClearBufferfv",
    "glClearBufferiv",
    "glClearBufferuiv",
    "glColorMask",
    "glColorMaski",
    "glCompileShader",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    "glCreateProgram",
    "glCreateShader",
    "glCullFace",
    "glDeleteBuffers",
    "glDeleteFramebuffers",
    "glDeleteProgram",
    "glDeleteRenderbuffers",
    "glDeleteSamplers",
    "glDeleteShader",
    "glDeleteTextures",
    "glDeleteVertexArrays",
    "glDepthFunc",
    "glDepthMask",
    "glDisable",
    "glDisableVertexAttribArray",
    "glDispatchCompute",
    "glDrawArrays",
    "glDrawArraysInstanced",
    "glDrawArraysInstancedBaseInstance",
    "glDrawBuffers",
    "glDrawElements",
    "glDrawElementsBaseVertex",
    "glDrawElementsInstanced",
    "glDrawElementsInstancedBaseVertex",
    "glDrawElementsInstancedBaseVertexBaseInstance",
    "glEnable",
    "glEnableVertexAttribArray",
    "glFramebufferRenderbuffer",
    "glFramebufferTexture2D",
    "glFramebufferTextureLayer",
    "glFrontFace",
    "glGenBuffers",
    "glGenFramebuffers",
    "glGenRenderbuffers",
    "glGenSamplers",
    "glGenTextures",
    "glGenVertexArrays",
    "glGetAttribLocation",
    "glGetError",
    "glGetIntegerv",
    "glGetProgramInfoLog",
    "glGetProgramiv",
    "glGetShaderInfoLog",
    "glGetShaderiv",
    "glGetStringi",
    "glGetUniformLocation",
    "glLinkProgram",
    "glMemoryBarrier",
    "glPixelStorei",
    "glPolygonOffset",
    "glReadBuffer",
    "glRenderbufferStorage",
    "glRenderbufferStorageMultisample",
    "glSamplerParameterf",
    "glSamplerParameterfv",
    "glSamplerParameteri",
    "glScissor",
    "glShaderSource",
    "glStencilFunc",
    "glStencilFuncSeparate",
    "glStencilMask",
    "glStencilOp",
    "glStencilOpSeparate",
    "glTexImage2D",
    "glTexImage2DMultisample",
    "glTexImage3D",
    "glTexImage3DMultisample",
    "glTexParameterf",
    "glTexParameterfv",
    "glTexParameteri",
    "glTexStorage2D",
    "glTexStorage2DMultisample",
    "glTexStorage3D",
    "glTexStorage3DMultisample",
    "glTexSubImage2D",
    "glTexSubImage3D",
    "glTextureView",
    "glUniform1fv",
    "glUniform1i",
    "glUniform1iv",
    "glUniform2fv",
    "glUniform2iv",
    "glUniform3fv",
    "glUniform3iv",
    "glUniform4fv",
    "glUniform4iv",
    "glUniformMatrix4fv",
    "glUseProgram",
    "glVertexAttribDivisor",
    "glVertexAttribIPointer",
    "glVertexAttribPointer",
    "glViewport",
};
